all : ctr64_asm ctrx_disasm ctrx_hsf ctr64_z64

clean:
	@make -f MakefileAsm clean
	@make -f MakefileDisasm clean
	@make -f MakefileHsf clean
	@make -f MakefileZ64 clean

ctr64_asm:
	make -f MakefileAsm

ctrx_disasm:
	make -f MakefileDisasm

ctrx_hsf:
	make -f MakefileHsf

ctr64_z64:
	make -f MakefileZ64